branches:
  except:
    - gridder
    - x
    - no_legion_subproject
dist: focal
language: cpp
env:
  global:
    - MAKEFLAGS="-j 2"
compiler:
  - gcc
before_install:
  - sudo apt-get install -y git-lfs gfortran libhdf5-dev libhdf5-103 flex bison liblapack-dev libcfitsio8 libcfitsio-dev wcslib-dev libwcs7 casacore-dev casacore-data doxygen libfftw3-single3 libfftw3-dev libyaml-cpp-dev
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.14/cmake-3.14.7-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.14.7-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.14.7-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
before_script:
  - mkdir build
  - cd build
  - cmake -DMAX_DIM=4 -DUSE_CASACORE=ON -DUSE_HDF5=ON ..
script:
  - make VERBOSE=1
  - make test
